######################
# Tokens Information #
######################

eth:
  coingecko_id: "ethereum"
bnb:
  coingecko_id: "binancecoin"
matic:
  coingecko_id: "matic-network"
avax:
  coingecko_id: "avalanche-2"
ftm:
  coingecko_id: "fantom"
glmr:
  coingecko_id: "moonbeam"
xdai:
  coingecko_id: "xdai"
okb:
  coingecko_id: "okb"
dev:
  redirect: "glmr"
oeth:
  redirect: "eth"
aeth:
  redirect: "eth"
next:
  coingecko_id: "connext"
usdc:
  coingecko_id: "usd-coin"
  is_stablecoin: true
  default_price: 1.0
usdt:
  coingecko_id: "tether"
  is_stablecoin: true
  default_price: 1.0
dai:
  coingecko_id: "dai"
  is_stablecoin: true
  default_price: 1.0
kp3r:
  coingecko_id: "keep3rv1"
klp:
  redirect: "eth"
xoc:
  coingecko_id: "tether"
  is_stablecoin: true
  default_price: 1.0
ixt:
  coingecko_id: "ix-token"
alusd:
  coingecko_id: "alchemix-usd"
  is_stablecoin: true
  default_price: 1.0
aleth:
  coingecko_id: "alchemix-eth"
alchemix:
  coingecko_id: "alchemix"
zoomer:
  coingecko_id: "zoomer"
radar:
  coingecko_id: "dappradar"
p8:
  default_price: 1.0
btrst:
  coingecko_id: "braintrust"
xeure:
  coingecko_id: "monerium-eur-money"
fraction:
  default_price: 17600
grumpycat:
  coingecko_id: "grumpy-cat-2c33af8d-87a8-4154-b004-0686166bdc45"
planetix:
  coingecko_id: "ix-token"
aurox:
  coingecko_id: "urus-token"
space:
  coingecko_id: "space-token-bsc"
olit:
  coingecko_id: "olit"
  default_price: 1.0
test:
  is_stablecoin: true
  default_price: 1.0
tkn:
  is_stablecoin: true
  default_price: 1.0
workshoptoken:
  default_price: 1.0
gastly-lp-geth:
  default_price: 1.0