######################
# Tokens Information #
######################

eth:
  coingecko_id: "ethereum"
bnb:
  coingecko_id: "binancecoin"
matic:
  coingecko_id: "matic-network"
avax:
  coingecko_id: "avalanche-2"
ftm:
  coingecko_id: "fantom"
glmr:
  coingecko_id: "moonbeam"
xdai:
  coingecko_id: "xdai"
metis:
  coingecko_id: "metis-token"
okb:
  coingecko_id: "okb"
dev:
  redirect: "glmr"
oeth:
  redirect: "eth"
aeth:
  redirect: "eth"
next:
  coingecko_id: "connext"
usdc:
  coingecko_id: "usd-coin"
  is_stablecoin: true
  default_price: 1.0
usdt:
  coingecko_id: "tether"
  is_stablecoin: true
  default_price: 1.0
dai:
  coingecko_id: "dai"
  is_stablecoin: true
  default_price: 1.0
kp3r:
  coingecko_id: "keep3rv1"
klp:
  redirect: "eth"
alusd:
  coingecko_id: "alchemix-usd"
  is_stablecoin: true
  default_price: 1.0
aleth:
  coingecko_id: "alchemix-eth"
alchemix:
  coingecko_id: "alchemix"
xoc:
  coingecko_id: "tether"
  is_stablecoin: true
  default_price: 1.0
ixt:
  coingecko_id: "ix-token"
planetix:
  redirect: "ixt"
radar:
  coingecko_id: "dappradar"
zoomer:
  coingecko_id: "zoomer"
btrst:
  coingecko_id: "braintrust"
xeure:
  coingecko_id: "monerium-eur-money"
grumpycat:
  coingecko_id: "grumpy-cat-2c33af8d-87a8-4154-b004-0686166bdc45"
aurox:
  coingecko_id: "urus-token"
space:
  coingecko_id: "space-token-bsc"
sdai:
  coingecko_id: "savings-dai"
inreth:
  coingecko_id: "inception-restaked-reth"
insteth:
  coingecko_id: "inception-restaked-steth"
ezeth:
  coingecko_id: "renzo-restaked-eth"
xezeth:
  redirect: "ezeth"
goat:
  coingecko_id: "goated"
arty:
  coingecko_id: "artyfact"
swpr:
  coingecko_id: "swapr"
fraction:
  coingecko_id: "fraction"
  default_price: 17600
nura:
  coingecko_id: "nura"
  default_price: 0.01
p8:
  coingecko_id: "p8"
  default_price: 0.01
olit:
  coingecko_id: "olit"
  default_price: 0.01
xgovt:
  coingecko_id: "xgovt"
  default_price: 0.01
esx:
  coingecko_id: "esx"
  default_price: 0.01
quid:
  coingecko_id: "quid"
  default_price: 0.01
test:
  is_stablecoin: true
  default_price: 1.0
tkn:
  is_stablecoin: true
  default_price: 1.0
workshoptoken:
  default_price: 0.01
gastly-lp-geth:
  default_price: 0.01